puppetlabs/puppetcpp

README.md, lib/include/puppet/lexer/number_token.hpp, lib/include/puppet/runtime/evaluator.hpp, lib/include/puppet/runtime/scope.hpp, lib/include/puppet/runtime/value.hpp, lib/src/lexer/number_token.cc, lib/src/runtime/expression_evaluator.cc, lib/src/runtime/operators.cc, lib/src/runtime/scope.cc
Implementing access expressions for String, Array, and Hash.
Fixing match variable scoping.
=> Implement access expressions and match variable scoping.

README.md, lib/include/puppet/runtime/operators.hpp, lib/include/puppet/runtime/value.hpp, lib/src/runtime/expression_evaluator.cc, lib/src/runtime/operators.cc, lib/src/runtime/value.cc
Implementing the unary splat operator and unfolding behavior for the
following constructs:
* Unfolding array elements to containing array
* Unfolding function arguments
* Unfolding case options
* Unfolding selectors
=> Implement the splat operator.

README.md, lib/src/runtime/expression_evaluator.cc, lib/src/runtime/functions/logging.cc, lib/src/runtime/value.cc, lib/src/runtime/yielder.cc
Implementing method call syntax and fixing a few bugs in the expression evaluator.
=> Implement method call and fix a few bugs

README.md, lib/CMakeLists.txt, lib/include/puppet/runtime/dispatcher.hpp, lib/include/puppet/runtime/expression_evaluator.hpp, lib/include/puppet/runtime/functions/fail.hpp, lib/include/puppet/runtime/functions/logging.hpp, lib/include/puppet/runtime/functions/split.hpp, lib/include/puppet/runtime/functions/with.hpp, lib/src/runtime/dispatcher.cc, lib/src/runtime/expression_evaluator.cc, lib/src/runtime/functions/fail.cc, lib/src/runtime/functions/logging.cc, lib/src/runtime/functions/split.cc, lib/src/runtime/functions/with.cc
Implementing the split function for string and regex overloads.
=> Implement the split function.

README.md, lib/src/runtime/functions/split.cc
Implementing the Regexp overload of the split function.
=> Implement Regexp overload of split function.

README.md, lib/CMakeLists.txt, lib/include/puppet/ast/case_expression.hpp, lib/include/puppet/compiler/grammar.hpp, lib/include/puppet/lexer/lexer.hpp, lib/include/puppet/runtime/types/array.hpp, lib/include/puppet/runtime/types/hash.hpp, lib/include/puppet/runtime/types/optional.hpp, lib/include/puppet/runtime/types/struct.hpp, lib/include/puppet/runtime/types/tuple.hpp, lib/include/puppet/runtime/types/variant.hpp, lib/include/puppet/runtime/values/array.hpp, lib/include/puppet/runtime/values/hash.hpp, lib/include/puppet/runtime/values/variable.hpp, lib/src/runtime/evaluators/access.cc, lib/src/runtime/scope.cc, lib/src/runtime/types/type.cc
This gets things building with GCC 5+.
=> Bug and build fixes

lib/include/puppet/ast/variable.hpp, lib/include/puppet/compiler/exceptions.hpp, lib/include/puppet/compiler/node.hpp, lib/include/puppet/compiler/parser.hpp, lib/src/ast/defined_type_expression.cc, lib/src/ast/parameter.cc, lib/src/ast/variable.cc, lib/src/runtime/context.cc, lib/src/runtime/definition_scanner.cc, lib/src/runtime/evaluators/basic.cc
Implementing a few name validation checks that Puppet performs.
=> Variable and parameter name validation.

README.md, lib/CMakeLists.txt, lib/include/puppet/runtime/catalog.hpp, lib/include/puppet/runtime/operators/relationship.hpp, lib/include/puppet/runtime/types/resource.hpp, lib/include/puppet/runtime/values/value.hpp, lib/src/compiler/node.cc, lib/src/runtime/catalog.cc, lib/src/runtime/expression_evaluator.cc, lib/src/runtime/operators/relationship.cc, lib/src/runtime/values/value.cc
Implementing the following metaparameters:
* before
* notify
* require
* subscribe
Implementing the following operators:
* ->
* ~>
* <-
* <~
This also implements dependency cycle detection.
Currently containment relationships are not implemented.
=> Implement relationship metaparameters and operators.

README.md, exe/main.cc, lib/CMakeLists.txt, lib/include/puppet/compiler/context.hpp, lib/include/puppet/compiler/node.hpp, lib/include/puppet/compiler/settings.hpp, lib/include/puppet/runtime/catalog.hpp, lib/include/puppet/runtime/functions/contain.hpp, lib/include/puppet/runtime/functions/require.hpp, lib/include/puppet/runtime/scope.hpp, lib/include/puppet/runtime/types/resource.hpp, lib/src/compiler/context.cc, lib/src/compiler/node.cc, lib/src/compiler/settings.cc, lib/src/facts/facter.cc, lib/src/facts/yaml.cc, lib/src/runtime/catalog.cc, lib/src/runtime/context.cc, lib/src/runtime/dispatcher.cc, lib/src/runtime/evaluators/catalog.cc, lib/src/runtime/executor.cc, lib/src/runtime/functions/contain.cc, lib/src/runtime/functions/require.cc, lib/src/runtime/operators/assignment.cc, lib/src/runtime/scope.cc
More implementation of the resource dependency graph.
This implements:
* The `stage` metaparameter.
* The `require` and `contain` functions.
* A `--graph` option for writing a DOT file representing a dependency graph.
This fixes the following:
* Bug whereby if a defined type or class parameter had a default value, the default value was always being used.
=> Implementation of resource graph.

lib/CMakeLists.txt, lib/include/puppet/runtime/functions/versioncmp.hpp, lib/src/runtime/dispatcher.cc, lib/src/runtime/functions/versioncmp.cc
This is probably the least idiomatic c++ anyone has ever written. Please feel free to tear this apart.
=> (Functions) Implement versioncmp function.

README.md
Updating the README to check off the versioncmp function.
=> Update README for versioncmp function.

README.md, exe/main.cc, lib/CMakeLists.txt, lib/include/puppet/ast/collection_expression.hpp, lib/include/puppet/compiler/context.hpp, lib/include/puppet/compiler/environment.hpp, lib/include/puppet/compiler/grammar.hpp, lib/include/puppet/compiler/module.hpp, lib/include/puppet/compiler/node.hpp, lib/include/puppet/compiler/settings.hpp, lib/include/puppet/lexer/lexer.hpp, lib/include/puppet/runtime/catalog.hpp, lib/include/puppet/runtime/context.hpp, lib/include/puppet/runtime/types/resource.hpp, lib/src/ast/collection_expression.cc, lib/src/ast/expression.cc, lib/src/compiler/context.cc, lib/src/compiler/environment.cc, lib/src/compiler/module.cc, lib/src/compiler/node.cc, lib/src/compiler/posix/settings.cc, lib/src/logging/logger.cc, lib/src/runtime/catalog.cc, lib/src/runtime/context.cc, lib/src/runtime/definition_scanner.cc, lib/src/runtime/evaluators/catalog.cc, lib/src/runtime/functions/logging.cc
Implements the following:
* Loading classes and defined types from modules.
* Virtual resource expressions.
* Exported resource expressions.
* Nested evaluation of defined types.
Note: there is currently no way to realize virtual resources; that work is in progress.
Fixes the following:
* Fix "error pointer" not pointing at the right column when the line has leading tabs.
* Fix lexing of regular expression literals not properly handling escaped "end of literal" characters.
* Fix parsing of collector expressions that contain nested attribute queries in parenthesis.
=> Module loading and virtual/exported resource expressions.

lib/include/puppet/compiler/grammar.hpp, lib/include/puppet/compiler/parser.hpp, lib/include/puppet/lexer/lexer.hpp, lib/include/puppet/lexer/token_id.hpp, lib/include/puppet/runtime/catalog.hpp, lib/src/compiler/parser.cc, lib/src/lexer/token_id.cc, lib/src/runtime/catalog.cc, lib/src/runtime/evaluators/catalog.cc, lib/src/runtime/executor.cc, lib/src/runtime/operators/relationship.cc, lib/src/runtime/string_interpolator.cc, lib/src/runtime/values/value.cc
This implements lazy evaluation for resource override and resource relationship expressions.
Also implemented is an improved error message if an unclosed comment token is encountered.
=> Implement lazy catalog expression evaluation.

README.md, lib/CMakeLists.txt, lib/include/puppet/runtime/catalog.hpp, lib/include/puppet/runtime/collectors/collector.hpp, lib/include/puppet/runtime/collectors/list_collector.hpp, lib/include/puppet/runtime/functions/realize.hpp, lib/src/runtime/catalog.cc, lib/src/runtime/collectors/collector.cc, lib/src/runtime/collectors/list_collector.cc, lib/src/runtime/dispatcher.cc, lib/src/runtime/functions/declare.cc, lib/src/runtime/functions/realize.cc
This implements the realize function by adding a "known list" collector that
gets run upon catalog finalization.  The resources in the list are realized
when the collector runs.
Fixing a bug in the require/include/contain functions where the argument wasn't
being deferenced properly.
=> Implement the realize function.

lib/src/runtime/collectors/query_evaluator.cc
Querying on 'title' should match the resource title and not a 'title' attribute
on the resource.  This fixes the query evaluator to properly check the
resource's title rather than an attribute.
=> Fix collection expressions that query on 'title'.

README.md, lib/CMakeLists.txt, lib/include/puppet/runtime/functions/defined.hpp, lib/src/compiler/node.cc, lib/src/runtime/dispatcher.cc, lib/src/runtime/evaluators/catalog.cc, lib/src/runtime/executor.cc, lib/src/runtime/functions/defined.cc
Implementing the `defined` function and also fixing some bugs.
=> Bug fixes and implementing the `defined` function.

.travis.yml, README.md, docker/Dockerfile
Adding a travis file to implement CI.
Also adding a Dockerfile for peterhuene/puppetcpp build environment used by
Travis.
=> Adding a travis file.

README.md, lib/CMakeLists.txt, lib/include/puppet/compiler/parser.hpp, lib/include/puppet/lexer/lexer.hpp, lib/include/puppet/lexer/token_id.hpp, lib/include/puppet/runtime/functions/reduce.hpp, lib/src/lexer/token_id.cc, lib/src/runtime/dispatcher.cc, lib/src/runtime/functions/each.cc, lib/src/runtime/functions/filter.cc, lib/src/runtime/functions/map.cc, lib/src/runtime/functions/reduce.cc
Implementing the `reduce` function and a few other minute clean-up fixes.
=> Implement the `reduce` function and other minor fixes.

README.md, lib/CMakeLists.txt, lib/include/puppet/compiler/attribute.hpp, lib/include/puppet/compiler/catalog.hpp, lib/include/puppet/compiler/evaluation/functions/tag.hpp, lib/include/puppet/compiler/evaluation/functions/tagged.hpp, lib/include/puppet/compiler/evaluation/scope.hpp, lib/include/puppet/compiler/resource.hpp, lib/src/compiler/attribute.cc, lib/src/compiler/catalog.cc, lib/src/compiler/evaluation/call_evaluator.cc, lib/src/compiler/evaluation/collectors/query_evaluator.cc, lib/src/compiler/evaluation/context.cc, lib/src/compiler/evaluation/dispatcher.cc, lib/src/compiler/evaluation/functions/declare.cc, lib/src/compiler/evaluation/functions/tag.cc, lib/src/compiler/evaluation/functions/tagged.cc, lib/src/compiler/evaluation/scope.cc, lib/src/compiler/resource.cc, lib/src/runtime/values/value.cc
Implementing tags in the catalog and related functions:
* tag
* tagged
=> Implement tags.

lib/include/puppet/runtime/types/struct.hpp, lib/include/puppet/runtime/values/hash.hpp, lib/include/puppet/runtime/values/wrapper.hpp, lib/src/compiler/environment.cc, lib/src/compiler/evaluation/access_evaluator.cc, lib/src/compiler/evaluation/context.cc, lib/src/compiler/evaluation/evaluator.cc, lib/src/compiler/evaluation/functions/each.cc, lib/src/compiler/evaluation/functions/filter.cc, lib/src/compiler/evaluation/functions/map.cc, lib/src/compiler/evaluation/functions/reduce.cc, lib/src/compiler/evaluation/operators/in.cc, lib/src/compiler/evaluation/operators/minus.cc, lib/src/compiler/evaluation/operators/plus.cc, lib/src/compiler/evaluation/scope.cc, lib/src/compiler/registry.cc, lib/src/compiler/settings.cc, lib/src/facts/facter.cc, lib/src/facts/yaml.cc, lib/src/runtime/types/hash.cc, lib/src/runtime/types/struct.cc, lib/src/runtime/values/hash.cc, lib/src/runtime/values/value.cc
Bug fixes:
* Fix `hash` so that it is insertion sort stable.
* Fix plus operator with `Hash` + `Array` to properly handle subarrays of size 1.
* Fix `Struct` to support `Optional[string]` and `NotUndef[string]` as keys to the hash.
=> Bug fixes.

lib/include/puppet/compiler/environment.hpp, lib/include/puppet/compiler/evaluation/dispatcher.hpp, lib/include/puppet/compiler/evaluation/scope.hpp, lib/src/compiler/environment.cc, lib/src/compiler/evaluation/call_evaluator.cc, lib/src/compiler/evaluation/dispatcher.cc, lib/src/compiler/evaluation/operators/assignment.cc, lib/src/compiler/evaluation/scope.cc, lib/src/facts/facter.cc
Adding a fallback function to the dispatcher if a Puppet function cannot be found.
Fixing assigned variables in scopes not keeping a reference on the AST for assignment context.
=> Two minor changes

README.md
Updating the CI badges in the README to point at the puppetlabs repo.
=> (maint) Update badges in README to puppetlabs repo.

README.md, lib/include/puppet/compiler/attribute.hpp, lib/include/puppet/compiler/catalog.hpp, lib/include/puppet/compiler/evaluation/context.hpp, lib/include/puppet/compiler/evaluation/evaluator.hpp, lib/include/puppet/compiler/evaluation/scope.hpp, lib/include/puppet/compiler/parser/rules.hpp, lib/include/puppet/compiler/resource.hpp, lib/src/compiler/attribute.cc, lib/src/compiler/catalog.cc, lib/src/compiler/environment.cc, lib/src/compiler/evaluation/context.cc, lib/src/compiler/evaluation/evaluator.cc, lib/src/compiler/evaluation/scope.cc, lib/src/compiler/resource.cc, lib/tests/fixtures/compiler/parser/good/sample.baseline, lib/tests/fixtures/compiler/parser/good/sample.pp
These commits implement resource default expression evaluation.
=> (NPUP-30) Implement resource default expression evaluation.

CMakeLists.txt, README.md, cmake/cotire.cmake, lib/CMakeLists.txt, lib/include/puppet/runtime/types/integer.hpp, lib/include/puppet/runtime/types/iterable.hpp, lib/include/puppet/runtime/values/type.hpp, lib/src/compiler/evaluation/access_evaluator.cc, lib/src/compiler/evaluation/evaluator.cc, lib/src/compiler/evaluation/functions/each.cc, lib/src/compiler/evaluation/functions/filter.cc, lib/src/compiler/evaluation/functions/map.cc, lib/src/compiler/evaluation/functions/reduce.cc, lib/src/runtime/types/integer.cc, lib/src/runtime/types/iterable.cc, lib/tests/fixtures/compiler/evaluation/iterable.baseline, lib/tests/fixtures/compiler/evaluation/iterable.pp
=> (NPUP-32) Implement Iterable type.

lib/CMakeLists.txt, lib/include/puppet/compiler/evaluation/functions/step.hpp, lib/include/puppet/runtime/values/iterator.hpp, lib/src/compiler/evaluation/dispatcher.cc, lib/src/compiler/evaluation/functions/step.cc, lib/src/runtime/values/iterator.cc, lib/tests/fixtures/compiler/evaluation/step.baseline, lib/tests/fixtures/compiler/evaluation/step.pp
This commit implements the Puppet `step` function.
=> (NPUP-36) Implement the step function.

docker/puppetcpp-ci/Dockerfile, docker/puppetcpp/Dockerfile
Adding Onigmo to the puppetcpp and puppetcpp-ci Dockerfiles.
=> (maint) Add Onigmo to CI Dockerfile.

README.md
Updating the codecov.io badge.
=> (maint) Update codecov.io badge.

lib/include/puppet/compiler/evaluation/evaluator.hpp, lib/include/puppet/runtime/values/regex.hpp, lib/include/puppet/runtime/values/value.hpp, lib/src/compiler/evaluation/evaluator.cc, lib/src/compiler/evaluation/operators/binary/in.cc, lib/src/compiler/evaluation/operators/binary/match.cc, lib/src/compiler/evaluation/operators/binary/not_match.cc, lib/src/compiler/evaluation/postfix_evaluator.cc, lib/src/runtime/values/regex.cc, lib/src/runtime/values/value.cc, lib/tests/fixtures/compiler/evaluation/match.baseline, lib/tests/fixtures/compiler/evaluation/match.pp
This commit implements deep matching against arrays and hashes for case and
selector expressions.
=> (NPUP-9) Implement deep matching in case and selector expressions.
