puppetlabs/puppetcpp

lib/src/runtime/operators.cc
Fixing invalid formatting of error message when evaluating a division by
zero.
=> Fix error message for division by zero.

lib/CMakeLists.txt, lib/include/puppet/ast/bare_word.hpp, lib/include/puppet/ast/expression.hpp, lib/include/puppet/ast/string.hpp, lib/include/puppet/parser/grammar.hpp, lib/src/ast/bare_word.cc, lib/src/ast/string.cc, lib/src/runtime/expression_evaluator.cc, lib/src/runtime/string_interpolator.cc
Fixing string interpolation that should handle the conversion of bare
words (may lead with underscore) into variables.  This fixes
interpolation of ${_foo}, ${_foo[0]} and ${_foo.bar}, where _foo should
be treated as a reference to variable $_foo.
This also fixes the parsing of bare words, which caused an unhandled
exception since string interpolation was implemented.  It also changes
the grammar such that the parser will now output "bare words" into the
AST instead of treating them as strings.  This allows us to handle the
above expressions.
This addresses GH issue #9.
=> Fix interpolation of variable names with leading underscores.

exe/main.cc, lib/include/puppet/runtime/expression_evaluator.hpp, lib/src/runtime/expression_evaluator.cc
This commit makes the expression evaluator behave more like Puppet's
with respect to evaluating unproductive expressions.
For example, '1+1' is an unproductive expression because it doesn't
change the state of the system.  Puppet detects these expressions and
treats them like an error, provided the expression isn't the last in a
block (which functions like a "return value").
This checking is actually more strict than Puppet's.  For example, the
expression '1 + ($a = 1)' is treated as productive by Puppet because the
subexpression $a = 1 is productive.  This implementation considers that
to be an error since the entire expression is unproductive even if the
subexpression is productive.
=> Prevent unproductive expression evaluation.

lib/CMakeLists.txt, lib/include/puppet/ast/case_expression.hpp, lib/include/puppet/ast/defaulted.hpp, lib/include/puppet/ast/expression.hpp, lib/include/puppet/ast/selector_expression.hpp, lib/include/puppet/parser/grammar.hpp, lib/include/puppet/runtime/value.hpp, lib/src/ast/case_expression.cc, lib/src/ast/defaulted.cc, lib/src/ast/selector_expression.cc, lib/src/runtime/expression_evaluator.cc, lib/src/runtime/functions/split.cc, lib/src/runtime/operators.cc, lib/src/runtime/value.cc
Fixes to bug fixes for empty regex matches.
Implementation of treating 'default' like 'undef' in the runtime.
=> Bug fixes and default handling.

README.md, lib/CMakeLists.txt, lib/include/puppet/runtime/functions/assert_type.hpp, lib/include/puppet/runtime/values/value.hpp, lib/src/runtime/dispatcher.cc, lib/src/runtime/expression_evaluator.cc, lib/src/runtime/functions/assert_type.cc, lib/src/runtime/functions/split.cc, lib/src/runtime/operators.cc, lib/src/runtime/values/value.cc, lib/src/runtime/yielder.cc
Implementing the assert_type function (NYI: String type names).
Changing get_type_name to get_type to return actual type instances.
=> Implement the assert_type function.

lib/CMakeLists.txt, lib/include/puppet/ast/access_expression.hpp, lib/include/puppet/ast/expression.hpp, lib/include/puppet/ast/expression_def.hpp, lib/include/puppet/ast/method_call_expression.hpp, lib/include/puppet/ast/postfix_expression.hpp, lib/include/puppet/ast/resource_expression.hpp, lib/include/puppet/ast/resource_override_expression.hpp, lib/include/puppet/ast/selector_expression.hpp, lib/include/puppet/parser/grammar.hpp, lib/src/ast/access_expression.cc, lib/src/ast/expression.cc, lib/src/ast/method_call_expression.cc, lib/src/ast/parameter.cc, lib/src/ast/postfix_expression.cc, lib/src/ast/resource_expression.cc, lib/src/ast/resource_override_expression.cc, lib/src/ast/selector_expression.cc, lib/src/runtime/expression_evaluator.cc, lib/src/runtime/functions/assert_type.cc, lib/src/runtime/string_interpolator.cc, lib/src/runtime/yielder.cc
Previously the grammar was defined such that postfix expressions could
only chain with expressions of the same type.
For example, access expressions could only chain together with other
access expressions.  So `$a[0][0]` was a valid expression, but `$a.with
|$x| { $x }[0]` was not.
This fixes the grammar such that postfix expressions are primary
expressions that have an initial primary expression and then N number of
postfix expressions that are evaluated in sequence, chained together.
This also fixes a bug in lambdas such that lambdas returning a match or
parameter variable (i.e. a variable in an ephemeral scope) failed to
copy the value into the return value.  This resulted in undefined
behavior when the variable was later accessed.
=> Fix postfix expressions.

lib/include/puppet/parser/grammar.hpp
The previous commit moved resource expressions out of statement
expressions and into primary expressions.  This caused ambiguity in
case expressions.
For example, this could be parsed as a case keyword followed by a
resource expression for a resource of type 'foo':
```
case foo {
} ...
```
The only catalog expression that should be allowed a primary expression
is the collection expression; all other catalog expressions are treated
as statement expressions.
=> Fix case expression parsing.

lib/include/puppet/compiler/grammar.hpp
Apparently the removal of the semantic action on primary_expression
broke parsing.  Adding back the seemingly useless assignment to what was
matched.
=> Fix primary expression parsing.

lib/include/puppet/compiler/token_pos.hpp
Accidentally checked in a comment where some functional code should have
been when I removed the phoenix function in favor of a `token_pos`
parser.
This fixes the parser so that it returns non-default contrusted token
positions.
=> Fix token position assignment in grammar.

lib/include/puppet/compiler/token_pos.hpp
The token_pos parser was not formatting what() in the same way the
token parser was. Therefore the parser was not outputing their values
correctly when an expectation failure was encountered at a token_pos in
the grammar.
=> Fix output of compiler errors when expectations fail on token_pos.

README.md, lib/include/puppet/runtime/context.hpp, lib/include/puppet/runtime/scope.hpp, lib/include/puppet/runtime/types/class.hpp, lib/include/puppet/runtime/types/resource.hpp, lib/src/runtime/catalog.cc, lib/src/runtime/context.cc, lib/src/runtime/evaluators/basic.cc, lib/src/runtime/evaluators/catalog.cc, lib/src/runtime/functions/split.cc, lib/src/runtime/scope.cc, lib/src/runtime/values/value.cc
Initial support for class definition expressions.  This does the
following:
* If the class derives from another, ensures the parent class has been
defined.
* Ensures the class hasn't previously been defined.
* Saves the class definition in the evaluation context.
Resource declarations for classes and declaration functions are
forthcoming.
This also fixes scope lookup for variables so that qualified names are
properly respected.
=> Implement class definition expressions.

README.md, lib/include/puppet/compiler/node.hpp, lib/include/puppet/runtime/context.hpp, lib/src/compiler/context.cc, lib/src/compiler/node.cc, lib/src/runtime/context.cc, lib/src/runtime/definition_scanner.cc, lib/src/runtime/evaluators/basic.cc, lib/src/runtime/evaluators/catalog.cc, lib/src/runtime/operators/match.cc
Implementing node definition expression evaluation.  This implements
default, named, and regex-based node definition expressions.
This also fixes the match operator where invalid regular expression
strings were not being properly handled.
=> Implement node definition expression evaluation.

lib/include/puppet/runtime/context.hpp, lib/src/runtime/context.cc, lib/src/runtime/expression_evaluator.cc
Node scope wasn't properly being respected by classes and defined types
declared in node scope; they were always using the top scope for a
parent (without class parents).
This also fixes the display name of the named scope to let the user know
which name matched (regex, string, or default).
=> Fix node scope not being respected.

lib/src/runtime/context.cc
Fixing node scope display name to show the matched string/pattern,
rather than always showing the node name.
=> Fix node display names to show the matched string/pattern.

README.md, lib/include/puppet/ast/case_expression.hpp, lib/include/puppet/ast/resource_expression.hpp, lib/include/puppet/compiler/grammar.hpp, lib/include/puppet/runtime/catalog.hpp, lib/include/puppet/runtime/context.hpp, lib/include/puppet/runtime/evaluators/catalog.hpp, lib/include/puppet/runtime/executor.hpp, lib/include/puppet/runtime/scope.hpp, lib/include/puppet/runtime/types/class.hpp, lib/include/puppet/runtime/types/resource.hpp, lib/include/puppet/runtime/values/value.hpp, lib/include/puppet/runtime/values/variable.hpp, lib/src/ast/case_expression.cc, lib/src/ast/resource_expression.cc, lib/src/runtime/catalog.cc, lib/src/runtime/context.cc, lib/src/runtime/definition_scanner.cc, lib/src/runtime/evaluators/basic.cc, lib/src/runtime/evaluators/catalog.cc, lib/src/runtime/evaluators/control_flow.cc, lib/src/runtime/executor.cc, lib/src/runtime/functions/include.cc, lib/src/runtime/functions/with.cc, lib/src/runtime/operators/assignment.cc, lib/src/runtime/operators/minus.cc, lib/src/runtime/operators/splat.cc, lib/src/runtime/scope.cc, lib/src/runtime/string_interpolator.cc, lib/src/runtime/values/value.cc
This implements the following:
* Implement Type and Resource['type'] in resource expressions.
* Implement support for resource expression default attributes.
* Implement resource metaparameter type checking.
* Implement stricter checks of class/defined type parameters.
* Implement attribute sharing between resources that are declared in the
same expressions.
* Implement setting all resource attributes in a class / define type's
evaluation scope.
* Improve error messages for class/defined type attributes with
mismatched types.
This fixes the following:
* Fix bug where as<T> was being invoked with pointers to values instead of refs.
* Fix resource expression bodies being unnecessarily copied during
evaluation.
* Fix splat of undef (correct: [], incorrect: [undef])
* Fix variable value ref …
=> Refactoring to resource expression evaluation.

lib/src/runtime/evaluators/catalog.cc
Class and defined type redeclarations should be an error.
For classes, it was silently succeeding.  For defined types, the error
message was unhelpful.
This was a regression from a recent refactoring of the catalog
expression evaluator.
This also fixes a place where a pointer was output in an error message
instead of the path it points to.
=> Fix class and defined type redeclarations.

lib/include/puppet/runtime/catalog.hpp, lib/src/runtime/catalog.cc, lib/src/runtime/evaluators/catalog.cc
The previous commit regressed defined type declarations by accidentally
searching for the defined type by title rather than by type name.  This fixes
that by taking the type name (expected to be lowercase for the map) as a
parameter when declaring the defined type.
Also removing unused catalog member from resource.  If we need a back reference
from resource to catalog, we can add it back in the future.
=> Fix defined type declaration not finding types.

lib/src/compiler/settings.cc
When run without arguments, the check for argc > 1 fails so the program options
map is not populated correctly with default values.  As a result, casting a
non-existent value to a logging level throws.
The fix is to not check for argc > 1 and modify the default constructor for
`puppet::compiler::settings` to populate the map by parsing a trivial
command line of just "puppetcpp".
This fixes GH-58.
=> Fix unhandled exception when puppetcpp is run without arguments.

lib/include/puppet/runtime/evaluators/access.hpp, lib/src/runtime/evaluators/access.cc
The expression `Foo['bar']['baz']` should return the value of attribute `baz`
on resource `Foo[bar]`.  This implements the support in the access evaluator.
=> Implement access operator on fully qualified resource and class types.

lib/src/runtime/evaluators/catalog.cc
The following code should print 'foo':
```
file {
default:
owner => foo
;
'/foo':
;
}
notice File['/foo'][owner]
```
However, it results in an error saying that owner is not a parameter on
`File['/foo']` (this itself is a bug, but it cannot be fixed until custom types
are supported).
This fixes the parent pointer of the attributes collection being set when no
attributes are present in a resource body.
=> Fix resources with empty bodies not inheriting default attributes.

exe/main.cc, lib/include/puppet/runtime/catalog.hpp, lib/src/runtime/catalog.cc
Dependency cycle detection was using the Tiernan algorithm for finding cycles
in the graph.  Tiernan doesn't scale for large resource sets, so this
commit replaces its usage with the Hawick circuits algorithm.
This also fixes an incorrect error message when cycles are detected.
=> Replace Tiernan with Hawick circuits algorithm.

lib/include/puppet/facts/facter.hpp, lib/src/runtime/functions/versioncmp.cc
Fixing the build for Linux builds with GCC.
The facter header file failed to include facter's collection header so
it was not building (not caught because of cached PCH on a different
platform).
GCC has issues with the implicit casts of long long to value.  Adding
some static casts to make the cast to int64_t explicit, which allows the
implicit cast to value.
=> Build fixes for Linux.

lib/include/puppet/runtime/catalog.hpp, lib/include/puppet/runtime/collectors/collector.hpp, lib/src/runtime/catalog.cc, lib/src/runtime/collectors/collector.cc, lib/src/runtime/collectors/list_collector.cc, lib/src/runtime/collectors/query_collector.cc
Virtual resources should not be added to the dependency graph until they are
realized.  This change delays adding a vertex to the graph until the resource
is realized.
=> Delay adding virtual resources to the dependency graph.

lib/src/compiler/environment.cc
Currently the compiler is attempting to parse any files in the environment's
manifests directory.  This change limits the parsing to only .pp files.
=> Limit default manifest files by .pp extension.

lib/include/puppet/runtime/values/value.hpp, lib/src/runtime/functions/each.cc, lib/src/runtime/functions/filter.cc, lib/src/runtime/values/value.cc
The filter and each methods were enumerating string arguments by bytes rather
than Unicode code points.  This fixes the functions to properly enumerate the
individual code points instead of the bytes.
=> Fix filter and each methods not properly enumerating Unicode strings.

README.md, lib/CMakeLists.txt, lib/include/puppet/runtime/functions/map.hpp, lib/src/runtime/dispatcher.cc, lib/src/runtime/functions/map.cc
This implements the `map` function to conform to the behavior of the Ruby
compiler.
=> Implement the `map` function.

README.md, lib/CMakeLists.txt, lib/include/puppet/runtime/types/not_undef.hpp, lib/include/puppet/runtime/values/type.hpp, lib/src/compiler/evaluation/access_evaluator.cc, lib/src/compiler/evaluation/evaluator.cc, lib/src/runtime/types/not_undef.cc
Implementing the Puppet `NotUndef` type.
Implement `NotUndef[string]` and `Optional[string]` expressions.
This fixes GitHub issues #25 and #83.
=> Implement the NotUndef type.

lib/include/puppet/compiler/parser/rules.hpp, lib/src/compiler/evaluation/functions/inline_epp.cc
The resource expression rule was greedily matching against a type without a
access expression, causing a failure when the parser encountered a resource
defaults expression.
The fix is to change the rule to require the type to have at least one access
expression to match the resource expression rule.  This allows the rule to
gracefully fail to parse and allow the resource defaults expression rule to
match.
Also a minor fix to the debug output of `inline_epp` (missing new line).
=> Fix parser rule for resource expression.

lib/include/puppet/runtime/values/value.hpp, lib/src/runtime/values/value.cc
Due to value also supporting boolean as a value type, the implicit conversion
from `char const*` to `bool` was being selected over the expected conversion to
`std::string`.
This fixes the unintentional assignment by defining an explicit constructor and
assignment operator for `char const*`.
=> Fix assignment of values from `char const*`.

lib/include/puppet/compiler/evaluation/evaluator.hpp, lib/include/puppet/compiler/lexer/lexer.hpp, lib/include/puppet/compiler/parser/parsers.hpp, lib/src/compiler/parser/parser.cc
Fixing the following in the parser:
* Error message for missing `}` in string interpolating was incorrect (output parser typeinfo instead of the expected token).
* EPP parsing was not strict on checking for a missing end tag for opening tags `<%` and `<%-`.
=> Parser bug fixes

lib/include/puppet/compiler/evaluation/evaluator.hpp, lib/include/puppet/compiler/lexer/lexer.hpp, lib/include/puppet/compiler/lexer/number_token.hpp, lib/include/puppet/runtime/types/floating.hpp, lib/include/puppet/runtime/values/value.hpp, lib/src/compiler/evaluation/access_evaluator.cc, lib/src/compiler/evaluation/evaluator.cc, lib/src/compiler/evaluation/operators/divide.cc, lib/src/compiler/evaluation/operators/greater.cc, lib/src/compiler/evaluation/operators/greater_equal.cc, lib/src/compiler/evaluation/operators/less.cc, lib/src/compiler/evaluation/operators/less_equal.cc, lib/src/compiler/evaluation/operators/minus.cc, lib/src/compiler/evaluation/operators/multiply.cc, lib/src/compiler/evaluation/operators/negate.cc, lib/src/compiler/evaluation/operators/plus.cc, lib/src/compiler/lexer/number_token.cc, lib/src/facts/facter.cc, lib/src/facts/yaml.cc, lib/src/runtime/types/floating.cc, lib/src/runtime/types/numeric.cc, lib/src/runtime/values/value.cc, lib/tests/lexer/lexer.cc
On 64-bit Windows, as well as all OSes on POWER, ARM, and SPARC, `long double` is actually just a plain old `double`. It's generally just misleading to anyone reading your code, for very little gain in the couple cases where it is actually a different type. It's better to use a type with more consistent behaviors across all platforms.
Even on x86 Linux and OSX (where it's 80-bits), it sucks. It can't be passed in register arguments, and it actually takes up 16 bytes for alignment reasons - both in structures and on the stack.
Looking further forward, if we wanted to try to make float evaluation more consistent across platforms we could start controlling rounding modes etc. We can't do that if we're using differently-sized floats on different OSes.
=> Switch `long double` to `double`

lib/include/puppet/compiler/lexer/lexer.hpp, lib/src/compiler/module.cc, lib/src/compiler/scanner.cc
C++11 introduced raw strings using `R"(...)"` as the default delimiter.  This
is great for regular expressions so that the strings don't have to double
escape escape sequences, making the regular expressions more readable.
This commit replaces the regular expressions in the lexer, module, and scanner
to use raw strings.
=> Use raw strings for all regular expression strings in the compiler.

docker/Dockerfile
Now that the fix is upstream, remove the use of a clone of facter and instead
use Facter master to build the container.
=> Remove usage of API fix branch from Dockerfile.

.travis.yml, CMakeLists.txt, docker/Dockerfile
Modify the build to optionally pass -coverage to the compiler.
Modify the Docker image to install the codecov utility.
Modify travis to use the codecov utility to upload the coverage data.
Add a debug and release build to the Travis matrix.
=> Enable code coverage collection with codecov.io.

cmake/FindFacter.cmake
There is no 'facter' header, so update to 'facter/version.h' to properly
locate Facter's include directory.
=> (maint) Update Facter header file name.

README.md, lib/include/puppet/compiler/ast/adapted.hpp, lib/include/puppet/compiler/ast/ast.hpp, lib/include/puppet/compiler/evaluation/evaluator.hpp, lib/include/puppet/compiler/parser/rules.hpp, lib/include/puppet/compiler/scanner.hpp, lib/src/compiler/ast/ast.cc, lib/src/compiler/evaluation/evaluator.cc, lib/src/compiler/scanner.cc, lib/tests/compiler/ast/ast.cc, lib/tests/fixtures/compiler/parser/good/functions.baseline, lib/tests/fixtures/compiler/parser/good/functions.pp
This commit implements Puppet functions in the parser.
Evaluation of function expressions are not yet implemented.  Compiling a
function expression will result in a "not yet implemented" error when
evaluating the resulting AST.
=> (NPUP-2) Implement Puppet functions in the parser.

CMakeLists.txt, README.md, lib/include/puppet/compiler/ast/adapted.hpp, lib/include/puppet/compiler/ast/ast.hpp, lib/include/puppet/compiler/evaluation/evaluator.hpp, lib/include/puppet/compiler/lexer/lexer.hpp, lib/include/puppet/compiler/lexer/token_id.hpp, lib/include/puppet/compiler/parser/rules.hpp, lib/include/puppet/compiler/scanner.hpp, lib/src/compiler/ast/ast.cc, lib/src/compiler/evaluation/evaluator.cc, lib/src/compiler/lexer/token_id.cc, lib/src/compiler/scanner.cc, lib/tests/compiler/ast/ast.cc, lib/tests/compiler/lexer/lexer.cc, lib/tests/fixtures/compiler/lexer/keywords.pp, lib/tests/fixtures/compiler/parser/good/orchestration.baseline, lib/tests/fixtures/compiler/parser/good/orchestration.pp
This implements the following expressions in the native parser:
* produces expressions
* consumes expressions
* application expressions
* site expressions
Evaluation of these expressions is not yet implemented; this only populates the
AST with information regarding those expressions.
=> (NPUP-3) Implement application orchestration in native parser.

README.md, lib/include/puppet/compiler/evaluation/context.hpp, lib/include/puppet/compiler/parser/parser.hpp, lib/include/puppet/runtime/types/callable.hpp, lib/include/puppet/runtime/types/tuple.hpp, lib/include/puppet/runtime/values/type.hpp, lib/src/compiler/evaluation/access_evaluator.cc, lib/src/compiler/evaluation/context.cc, lib/src/compiler/evaluation/functions/assert_type.cc, lib/src/compiler/evaluation/scope.cc, lib/src/compiler/parser/parser.cc, lib/src/runtime/types/callable.cc, lib/src/runtime/types/struct.cc, lib/src/runtime/types/tuple.cc, lib/src/runtime/types/variant.cc, lib/src/runtime/values/type.cc, lib/tests/fixtures/compiler/parser/good/sample.baseline, lib/tests/fixtures/compiler/parser/good/sample.pp
Implementing the `Callable` type and the relevant access operator for it.
The syntax for the `Callable` type is:
`Callable[Arg1Type, Arg2Type, ..., ArgNType, min, max, BlockType]`
This does not yet include the work to support return types in `Callable` signatures as the design has not yet been finalized.  This gets to current parity with the Ruby implementation.
=> (NPUP-4) Implementing the `Callable` type and the relevant access operator for it.

lib/include/puppet/compiler/attribute.hpp, lib/src/compiler/attribute.cc, lib/src/compiler/evaluation/call_evaluator.cc, lib/src/compiler/resource.cc, lib/tests/fixtures/compiler/parser/good/sample.baseline, lib/tests/fixtures/compiler/parser/good/sample.pp
This fixes the call evaluator to properly evaluate a class or defined type's
parameters in declaration order, allowing later parameters to reference earlier
ones.
Example:
```
class foo($param1 = foo, $param2 = "${param1}bar") {
notice $param2
}
include foo
```
This should output "foobar" and not "bar" because the evaluation order of the
parameters should be left-to-right, meaning $param1 gets set in scope before
$param2's default value is evaluated.
This also fixes the evaluator not properly handling duplicate parameter names
in classes and defined types.
=> (NPUP-13) Allow class & defined type parameters to reference earlier ones.

lib/include/puppet/compiler/evaluation/call_evaluator.hpp, lib/src/compiler/evaluation/call_evaluator.cc, lib/tests/fixtures/compiler/parser/good/sample.baseline, lib/tests/fixtures/compiler/parser/good/sample.pp
When evaluating parameter default value expressions, a new match scope should
be used to prevent match scope variables "leaking" into the evaluation of the
following parameter defaults or into the body of the class, defined type, or
function.
This commit extracts out where the default value was evaluated and wraps it
with a utility member function that creates a new match scope.  Creating a new
match scope is efficient, so this will add no perceivable overhead to the call
evaluator.
This also fixes the same issue when evaluating the type expressions for
parameters.
=> (NPUP-14) Evaluate parameter default values in new match scope.

lib/include/puppet/compiler/environment.hpp, lib/include/puppet/compiler/finder.hpp, lib/include/puppet/compiler/node.hpp, lib/include/puppet/options/commands/compile.hpp, lib/src/compiler/environment.cc, lib/src/compiler/finder.cc, lib/src/compiler/node.cc, lib/src/options/commands/compile.cc, lib/src/options/commands/parse.cc, lib/tests/compiler/environment.cc
This fixes the `manifest` setting, when a directory (which is the default), to
recursively search for manifests in a deterministic order.
This commit removes the logic in the environment for searching for manifests
and consolidates the logic into the finder class.
=> (NPUP-24) Fix environment manifest search to be recursive.

lib/src/compiler/registry.cc
Fixing two bugs in class evaluation:
1. Leading `::` in a parent class name would cause an unhandled exception.
2. Confusing error message when there is a circular class inheritance.
=> (NPUP-26, NPUP-27) Fix bugs in class evaluation.

lib/include/puppet/compiler/parser/rules.hpp, lib/tests/fixtures/compiler/parser/good/collector.baseline, lib/tests/fixtures/compiler/parser/good/collector.pp
The parser rule for resource override expressions did not support collectors,
resulting in an incorrect parse of a collector expression followed by a hash.
This commit updates the rule to support collectors in resource override
expressions.
=> (NPUP-29) Fix parse of resource override expressions with collectors.

lib/include/puppet/compiler/lexer/lexer.hpp, lib/tests/fixtures/compiler/parser/good/sample.baseline, lib/tests/fixtures/compiler/parser/good/sample.pp
The lexer was not properly lexing interpolation sequences where whitespace
surrounded what should be a variable token.  A name token was being output
instead.
The fix is to ignore whitespace in the variable check state and do the
lookahead in a new state that can ignore trailing whitespace.
=> (NPUP-31) Fix interpolation of variables containing whitespace.

CMakeLists.txt, README.md, cmake/cotire.cmake, exe/CMakeLists.txt, lib/CMakeLists.txt, lib/tests/CMakeLists.txt
This commit adds cotire back to the build because its removal caused build
times to nearly double in CI without precompiled headers.
Updating the README with the caveats of using PCH with ccache and Ninja.
=> (maint) Reinstate cotire in the build.

README.md, lib/CMakeLists.txt, lib/include/puppet/compiler/evaluation/functions/reverse_each.hpp, lib/src/compiler/evaluation/dispatcher.cc, lib/src/compiler/evaluation/functions/reverse_each.cc, lib/src/runtime/types/iterable.cc, lib/tests/fixtures/compiler/evaluation/each.baseline, lib/tests/fixtures/compiler/evaluation/each.pp, lib/tests/fixtures/compiler/evaluation/filter.baseline, lib/tests/fixtures/compiler/evaluation/filter.pp, lib/tests/fixtures/compiler/evaluation/iterable.pp, lib/tests/fixtures/compiler/evaluation/iterator.baseline, lib/tests/fixtures/compiler/evaluation/iterator.pp, lib/tests/fixtures/compiler/evaluation/map.baseline, lib/tests/fixtures/compiler/evaluation/map.pp, lib/tests/fixtures/compiler/evaluation/reduce.baseline, lib/tests/fixtures/compiler/evaluation/reduce.pp, lib/tests/fixtures/compiler/evaluation/reverse_each.baseline, lib/tests/fixtures/compiler/evaluation/reverse_each.pp, lib/tests/fixtures/compiler/evaluation/type_comparisons.pp
This implements the `reverse_each` function.
This behaves a little differently from the Ruby implementation in that `reverse_each` has the same signature as `each`, but simply iterates in reverse.  Thus it preserves the "iterate with index", "iterate value" and "iterate key, value" (Hash) semantics of `each`.
The difference in behavior can be viewed as `reverse_each` having a new overload that takes a two-parameter block; if a one-parameter block is passed (the only signature currently supported in the Ruby implementation), then the behavior is identical.
=> (NPUP-35) Implement the `reverse_each` function.

CMakeLists.txt, README.md, cmake/FindEditline.cmake, cmake/FindReadline.cmake, docker/puppetcpp-ci/Dockerfile, docker/puppetcpp/Dockerfile, lib/CMakeLists.txt, lib/src/options/commands/repl.cc
Replacing references to the Readline library with the Editline library as the
latter has a compatible license.
=> (NPUP-40) Replace references to GNU Readline with Editline.

codecov.yml
codecov.io, the site we use for CI coverage, has migrated settings to a YAML
file.  This commit restores the settings that were previously being set via the
website.
=> (maint) Add codecov.yml for code coverage settings.

README.md
Adding a buildstats.info badge to the README to display a historical view of
build statuses.
=> (maint) Add buildstats badge to the README.

README.md, docker/puppetcpp/Dockerfile, lib/CMakeLists.txt
Updating the README to fix spelling mistake and check off features that have
been implemented.
Also fixing the install target to include `LIB_SUFFIX` so that the library is
installed into the correct location on platforms that have a lib64.
=> (maint) Fixes to README and install procedure.

lib/src/compiler/evaluation/functions/descriptor.cc, lib/src/compiler/scanner.cc
This commit allows private functions in the environment where previously there
was a requirement that private functions only be defined in modules.
Now if a private environment function is called, an appropriate error message
is displayed to the user.
=> (NPUP-37) Allow the environment to have private functions.

lib/include/puppet/compiler/ast/visitors/validation.hpp, lib/src/compiler/ast/visitors/validation.cc, lib/tests/fixtures/compiler/parser/illegal_app_name.baseline, lib/tests/fixtures/compiler/parser/illegal_app_name.pp, lib/tests/fixtures/compiler/parser/illegal_func_name.baseline, lib/tests/fixtures/compiler/parser/illegal_func_name.pp, lib/tests/fixtures/compiler/parser/illegal_type_alias_name.baseline, lib/tests/fixtures/compiler/parser/illegal_type_alias_name.pp
This commit adds a validation check for functions, applications, and alias
names so that they may not start with '::'.
=> (NPUP-44) Validate function, application, and type alias names.

docker/puppetcpp/Dockerfile
This commit fixes the Dockerfile for puppetcpp so that the entrypoint uses the
correct path to the executable.
=> (maint) Update incorrect docker entrypoint path.

lib/src/compiler/evaluation/functions/each.cc, lib/src/compiler/evaluation/functions/filter.cc, lib/src/compiler/evaluation/functions/map.cc, lib/src/compiler/evaluation/functions/reduce.cc, lib/src/compiler/evaluation/functions/reverse_each.cc, lib/src/compiler/evaluation/functions/step.cc, lib/tests/fixtures/compiler/parser/return_in_interpolation.baseline, lib/tests/fixtures/compiler/parser/return_in_interpolation.pp
This commit fixes an unnecessary copy of return values from within the
iterating functions.
Also fixed was a missing brace that caused an incorrect test baseline for
testing using a return statement in an interpolated string.  The test and
baseline have been updated.
=> (maint) Fix unnecessary copy of return values.

lib/CMakeLists.txt, lib/src/compiler/evaluation/functions/alert.cc
This PR installs headers with the install target and removes a meaningless prefix from logged messages when a log function is called from a scope without an associated resource (i.e. when not compiling for a catalog).
=> Minor changes to support consumers of the C API.
